/* Generated by Yosys 0.7 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "cordic_ctl.v:1" *)
module cordic_ctl(ck, raz, wr_axy_p, a_p, wok_axy_p, rd_nxy_p, rok_nxy_p, get_p, calc_p, mkc_p, place_p, a_lt_0_p, quadrant_p, i_p);
  (* src = "cordic_ctl.v:119" *)
  wire _000_;
  (* src = "cordic_ctl.v:129" *)
  wire _001_;
  (* src = "cordic_ctl.v:114" *)
  wire _002_;
  (* src = "cordic_ctl.v:124" *)
  wire _003_;
  (* src = "cordic_ctl.v:109" *)
  wire _004_;
  (* src = "cordic_ctl.v:104" *)
  wire _005_;
  (* src = "cordic_ctl.v:80" *)
  wire [15:0] _006_;
  (* src = "cordic_ctl.v:70" *)
  wire [15:0] _007_;
  (* src = "cordic_ctl.v:65" *)
  wire [2:0] _008_;
  (* src = "cordic_ctl.v:90" *)
  wire [1:0] _009_;
  (* src = "cordic_ctl.v:80" *)
  wire [15:0] _010_;
  (* src = "cordic_ctl.v:70" *)
  wire [15:0] _011_;
  (* src = "cordic_ctl.v:80" *)
  wire [15:0] _012_;
  (* src = "cordic_ctl.v:70" *)
  wire [15:0] _013_;
  (* src = "cordic_ctl.v:80" *)
  wire [15:0] _014_;
  (* src = "cordic_ctl.v:80" *)
  wire [15:0] _015_;
  (* src = "cordic_ctl.v:80" *)
  wire [15:0] _016_;
  (* src = "cordic_ctl.v:67" *)
  wire [2:0] _017_;
  (* src = "cordic_ctl.v:74" *)
  wire [15:0] _018_;
  (* src = "cordic_ctl.v:92" *)
  wire [1:0] _019_;
  (* src = "cordic_ctl.v:131" *)
  wire _020_;
  (* src = "cordic_ctl.v:158" *)
  wire _021_;
  (* src = "cordic_ctl.v:160" *)
  wire _022_;
  (* src = "cordic_ctl.v:160" *)
  wire _023_;
  (* src = "cordic_ctl.v:161" *)
  wire _024_;
  (* src = "cordic_ctl.v:161" *)
  wire _025_;
  (* src = "cordic_ctl.v:162" *)
  wire _026_;
  (* src = "cordic_ctl.v:162" *)
  wire _027_;
  (* src = "cordic_ctl.v:163" *)
  wire _028_;
  (* src = "cordic_ctl.v:163" *)
  wire _029_;
  (* src = "cordic_ctl.v:73" *)
  wire _030_;
  (* src = "cordic_ctl.v:74" *)
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire [2:0] _041_;
  wire [2:0] _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  (* src = "cordic_ctl.v:159" *)
  wire _051_;
  (* src = "cordic_ctl.v:160" *)
  wire _052_;
  (* src = "cordic_ctl.v:87" *)
  wire _053_;
  (* src = "cordic_ctl.v:158" *)
  wire _054_;
  (* src = "cordic_ctl.v:162" *)
  wire _055_;
  (* src = "cordic_ctl.v:163" *)
  wire _056_;
  (* src = "cordic_ctl.v:73" *)
  wire _057_;
  (* src = "cordic_ctl.v:67" *)
  wire _058_;
  wire [2:0] _059_;
  wire [15:0] _060_;
  wire [15:0] _061_;
  wire [15:0] _062_;
  wire [15:0] _063_;
  wire [15:0] _064_;
  wire [15:0] _065_;
  wire [15:0] _066_;
  wire [15:0] _067_;
  wire [15:0] _068_;
  wire [15:0] _069_;
  wire [15:0] _070_;
  wire [15:0] _071_;
  wire [15:0] _072_;
  wire [15:0] _073_;
  wire [15:0] _074_;
  wire [15:0] _075_;
  wire [15:0] _076_;
  wire [15:0] _077_;
  wire [15:0] _078_;
  wire [15:0] _079_;
  wire [15:0] _080_;
  wire [15:0] _081_;
  wire [15:0] _082_;
  wire [15:0] _083_;
  wire [15:0] _084_;
  wire [15:0] _085_;
  wire [1:0] _086_;
  (* src = "cordic_ctl.v:73" *)
  wire [15:0] _087_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [2:0] _088_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _089_;
  wire [15:0] _090_;
  (* src = "<techmap.v>:258" *)
  wire [15:0] _091_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _092_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _093_;
  wire [15:0] _094_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _095_;
  wire [15:0] _096_;
  (* src = "<techmap.v>:260" *)
  wire [15:0] _097_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _098_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _099_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _100_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _101_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _102_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _103_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _104_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _105_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _106_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _107_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _108_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _109_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _110_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _111_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _112_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _113_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _114_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _115_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _116_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _117_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _118_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _119_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _120_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _121_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _122_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _123_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _124_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _125_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _126_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _127_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _128_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _129_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _130_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _131_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _132_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _133_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _134_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _135_;
  (* src = "<techmap.v>:260" *)
  wire [15:0] _136_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _137_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _138_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _139_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _140_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _141_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _142_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _143_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _144_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _145_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _146_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _147_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _148_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _149_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _150_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _151_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _152_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _153_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _154_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _155_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _156_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _157_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _158_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _159_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _160_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _161_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _162_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _163_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _164_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _165_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _166_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _167_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _168_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _169_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _170_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _171_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _172_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _173_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _174_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _175_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _176_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _177_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _178_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _179_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _180_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _181_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _182_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _183_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _184_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _185_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _186_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _187_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _188_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _189_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _190_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _191_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _192_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _193_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _194_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _195_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _196_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _197_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _198_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _199_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _200_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _201_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _202_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _203_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _204_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _205_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _206_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _207_;
  (* src = "cordic_ctl.v:44" *)
  reg [15:0] a;
  (* src = "cordic_ctl.v:37" *)
  wire a_lt_0;
  (* src = "cordic_ctl.v:14" *)
  output a_lt_0_p;
  (* src = "cordic_ctl.v:46" *)
  wire [15:0] a_mpidiv2;
  (* src = "cordic_ctl.v:6" *)
  input [9:0] a_p;
  (* src = "cordic_ctl.v:45" *)
  wire [15:0] atan;
  (* src = "cordic_ctl.v:30" *)
  reg calc;
  (* src = "cordic_ctl.v:11" *)
  output calc_p;
  (* src = "cordic_ctl.v:3" *)
  input ck;
  (* src = "cordic_ctl.v:47" *)
  wire fsm_def_14;
  (* src = "cordic_ctl.v:26" *)
  reg get;
  (* src = "cordic_ctl.v:10" *)
  output get_p;
  (* src = "cordic_ctl.v:42" *)
  reg [2:0] i;
  (* src = "cordic_ctl.v:16" *)
  output [2:0] i_p;
  (* src = "cordic_ctl.v:32" *)
  reg mkc;
  (* src = "cordic_ctl.v:12" *)
  output mkc_p;
  (* src = "cordic_ctl.v:43" *)
  wire [15:0] n_a;
  (* src = "cordic_ctl.v:29" *)
  wire n_calc;
  (* src = "cordic_ctl.v:25" *)
  wire n_get;
  (* src = "cordic_ctl.v:41" *)
  wire [2:0] n_i;
  (* src = "cordic_ctl.v:31" *)
  wire n_mkc;
  (* src = "cordic_ctl.v:27" *)
  wire n_norm;
  (* src = "cordic_ctl.v:33" *)
  wire n_place;
  (* src = "cordic_ctl.v:35" *)
  wire n_put;
  (* src = "cordic_ctl.v:39" *)
  wire [1:0] n_quadrant;
  (* src = "cordic_ctl.v:28" *)
  reg norm;
  (* src = "cordic_ctl.v:34" *)
  reg place;
  (* src = "cordic_ctl.v:13" *)
  output place_p;
  (* src = "cordic_ctl.v:36" *)
  reg put;
  (* src = "cordic_ctl.v:40" *)
  reg [1:0] quadrant;
  (* src = "cordic_ctl.v:38" *)
  wire quadrant_0;
  (* src = "cordic_ctl.v:15" *)
  output [1:0] quadrant_p;
  (* src = "cordic_ctl.v:4" *)
  input raz;
  (* src = "cordic_ctl.v:8" *)
  input rd_nxy_p;
  (* src = "cordic_ctl.v:9" *)
  output rok_nxy_p;
  (* src = "cordic_ctl.v:24" *)
  wire rtldef_0;
  (* src = "cordic_ctl.v:23" *)
  wire rtldef_1;
  (* src = "cordic_ctl.v:22" *)
  wire rtldef_2;
  (* src = "cordic_ctl.v:21" *)
  wire rtldef_3;
  (* src = "cordic_ctl.v:20" *)
  wire rtldef_4;
  (* src = "cordic_ctl.v:19" *)
  wire rtldef_5;
  (* src = "cordic_ctl.v:18" *)
  wire [15:0] rtlexts_0;
  (* src = "cordic_ctl.v:7" *)
  output wok_axy_p;
  (* src = "cordic_ctl.v:5" *)
  input wr_axy_p;
  assign _043_ = _032_ |(* src = "cordic_ctl.v:81" *)  i[2];
  assign _044_ = _033_ |(* src = "cordic_ctl.v:82" *)  i[2];
  assign _046_ = _035_ |(* src = "cordic_ctl.v:84" *)  i[2];
  assign _032_ = i[0] |(* src = "cordic_ctl.v:85" *)  i[1];
  assign _047_ = _032_ |(* src = "cordic_ctl.v:85" *)  _042_[2];
  assign _033_ = _017_[0] |(* src = "cordic_ctl.v:86" *)  i[1];
  assign _048_ = _033_ |(* src = "cordic_ctl.v:86" *)  _042_[2];
  assign _049_ = _034_ |(* src = "cordic_ctl.v:87" *)  _042_[2];
  assign _034_ = i[0] |(* src = "cordic_ctl.v:160" *)  _041_[1];
  assign _045_ = _034_ |(* src = "cordic_ctl.v:160" *)  i[2];
  assign _035_ = _017_[0] |(* src = "cordic_ctl.v:161" *)  _041_[1];
  assign _050_ = _035_ |(* src = "cordic_ctl.v:161" *)  _042_[2];
  assign fsm_def_14 = ~(* src = "cordic_ctl.v:157" *) raz;
  assign _051_ = ~(* src = "cordic_ctl.v:160" *) _045_;
  assign _052_ = ~(* src = "cordic_ctl.v:161" *) _050_;
  assign _085_[0] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[0] : 1'b1;
  assign _085_[1] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[1] : 1'b1;
  assign _085_[2] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[2] : 1'b0;
  assign _085_[3] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[3] : 1'b1;
  assign _085_[4] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[4] : 1'b1;
  assign _085_[5] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[15] : 1'b1;
  assign _085_[15] = _044_ ? (* src = "cordic_ctl.v:82" *) _010_[15] : 1'b0;
  assign _008_[0] = _036_ ? (* src = "cordic_ctl.v:66" *) _059_[0] : 1'bx;
  assign _008_[1] = _036_ ? (* src = "cordic_ctl.v:66" *) _059_[1] : 1'bx;
  assign _008_[2] = _036_ ? (* src = "cordic_ctl.v:66" *) _059_[2] : 1'bx;
  assign _010_[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _084_[0] : 1'bx;
  assign _010_[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _084_[1] : 1'bx;
  assign _010_[2] = _043_ ? (* src = "cordic_ctl.v:81" *) _084_[2] : 1'bx;
  assign _010_[3] = _043_ ? (* src = "cordic_ctl.v:81" *) _084_[3] : 1'bx;
  assign _010_[4] = _043_ ? (* src = "cordic_ctl.v:81" *) _084_[4] : 1'bx;
  assign _010_[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _084_[15] : 1'bx;
  assign _084_[0] = _044_ ? (* src = "cordic_ctl.v:82" *) _083_[0] : 1'bx;
  assign _084_[1] = _044_ ? (* src = "cordic_ctl.v:82" *) _083_[1] : 1'bx;
  assign _084_[2] = _044_ ? (* src = "cordic_ctl.v:82" *) _083_[2] : 1'bx;
  assign _084_[3] = _044_ ? (* src = "cordic_ctl.v:82" *) _083_[3] : 1'bx;
  assign _084_[4] = _044_ ? (* src = "cordic_ctl.v:82" *) _083_[4] : 1'bx;
  assign _084_[15] = _044_ ? (* src = "cordic_ctl.v:82" *) _083_[15] : 1'bx;
  assign n_i[0] = _036_ ? (* src = "cordic_ctl.v:66" *) _008_[0] : 1'b0;
  assign n_i[1] = _036_ ? (* src = "cordic_ctl.v:66" *) _008_[1] : 1'b0;
  assign n_i[2] = _036_ ? (* src = "cordic_ctl.v:66" *) _008_[2] : 1'b0;
  assign _083_[0] = _045_ ? (* src = "cordic_ctl.v:83" *) _012_[0] : 1'b1;
  assign _083_[1] = _045_ ? (* src = "cordic_ctl.v:83" *) _012_[1] : 1'b1;
  assign _083_[2] = _045_ ? (* src = "cordic_ctl.v:83" *) _012_[2] : 1'b1;
  assign _083_[3] = _045_ ? (* src = "cordic_ctl.v:83" *) _012_[3] : 1'b1;
  assign _083_[4] = _045_ ? (* src = "cordic_ctl.v:83" *) _012_[4] : 1'b1;
  assign _083_[15] = _045_ ? (* src = "cordic_ctl.v:83" *) _012_[15] : 1'b0;
  assign _060_[0] = _040_ ? (* src = "cordic_ctl.v:74" *) a[0] : _018_[0];
  assign _060_[1] = _040_ ? (* src = "cordic_ctl.v:74" *) a[1] : _018_[1];
  assign _060_[2] = _040_ ? (* src = "cordic_ctl.v:74" *) a[2] : _018_[2];
  assign _060_[3] = _040_ ? (* src = "cordic_ctl.v:74" *) a[3] : _018_[3];
  assign _060_[4] = _040_ ? (* src = "cordic_ctl.v:74" *) a[4] : _018_[4];
  assign _060_[5] = _040_ ? (* src = "cordic_ctl.v:74" *) a[5] : _018_[5];
  assign _060_[6] = _040_ ? (* src = "cordic_ctl.v:74" *) a[6] : _018_[6];
  assign _060_[7] = _040_ ? (* src = "cordic_ctl.v:74" *) a[7] : _018_[7];
  assign _060_[8] = _040_ ? (* src = "cordic_ctl.v:74" *) a[8] : _018_[8];
  assign _060_[9] = _040_ ? (* src = "cordic_ctl.v:74" *) a[9] : _018_[9];
  assign _060_[10] = _040_ ? (* src = "cordic_ctl.v:74" *) a[10] : _018_[10];
  assign _060_[11] = _040_ ? (* src = "cordic_ctl.v:74" *) a[11] : _018_[11];
  assign _060_[12] = _040_ ? (* src = "cordic_ctl.v:74" *) a[12] : _018_[12];
  assign _060_[13] = _040_ ? (* src = "cordic_ctl.v:74" *) a[13] : _018_[13];
  assign _060_[14] = _040_ ? (* src = "cordic_ctl.v:74" *) a[14] : _018_[14];
  assign _060_[15] = _040_ ? (* src = "cordic_ctl.v:74" *) a[15] : _018_[15];
  assign _061_[0] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[0] : 1'bx;
  assign _061_[1] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[1] : 1'bx;
  assign _061_[2] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[2] : 1'bx;
  assign _061_[3] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[3] : 1'bx;
  assign _061_[4] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[4] : 1'bx;
  assign _061_[5] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[5] : 1'bx;
  assign _061_[6] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[6] : 1'bx;
  assign _061_[7] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[7] : 1'bx;
  assign _061_[8] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[8] : 1'bx;
  assign _061_[9] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[9] : 1'bx;
  assign _061_[10] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[10] : 1'bx;
  assign _061_[11] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[11] : 1'bx;
  assign _061_[12] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[12] : 1'bx;
  assign _061_[13] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[13] : 1'bx;
  assign _061_[14] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[14] : 1'bx;
  assign _061_[15] = _039_ ? (* src = "cordic_ctl.v:73" *) _060_[15] : 1'bx;
  assign _059_[0] = _037_ ? (* src = "cordic_ctl.v:67" *) i[0] : _017_[0];
  assign _059_[1] = _037_ ? (* src = "cordic_ctl.v:67" *) i[1] : _017_[1];
  assign _059_[2] = _037_ ? (* src = "cordic_ctl.v:67" *) i[2] : _017_[2];
  assign _080_[0] = _046_ ? (* src = "cordic_ctl.v:84" *) _014_[0] : 1'b0;
  assign _080_[1] = _046_ ? (* src = "cordic_ctl.v:84" *) _014_[1] : 1'b0;
  assign _080_[2] = _046_ ? (* src = "cordic_ctl.v:84" *) _014_[2] : 1'b0;
  assign _080_[3] = _046_ ? (* src = "cordic_ctl.v:84" *) _014_[3] : 1'b0;
  assign _080_[4] = _046_ ? (* src = "cordic_ctl.v:84" *) _014_[15] : 1'b1;
  assign _080_[15] = _046_ ? (* src = "cordic_ctl.v:84" *) _014_[15] : 1'b0;
  assign _014_[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _079_[0] : 1'bx;
  assign _014_[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _079_[1] : 1'bx;
  assign _014_[2] = _043_ ? (* src = "cordic_ctl.v:81" *) _079_[2] : 1'bx;
  assign _014_[3] = _043_ ? (* src = "cordic_ctl.v:81" *) _079_[3] : 1'bx;
  assign _014_[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _079_[15] : 1'bx;
  assign _079_[0] = _044_ ? (* src = "cordic_ctl.v:82" *) _078_[0] : 1'bx;
  assign _079_[1] = _044_ ? (* src = "cordic_ctl.v:82" *) _078_[1] : 1'bx;
  assign _079_[2] = _044_ ? (* src = "cordic_ctl.v:82" *) _078_[2] : 1'bx;
  assign _079_[3] = _044_ ? (* src = "cordic_ctl.v:82" *) _078_[3] : 1'bx;
  assign _079_[15] = _044_ ? (* src = "cordic_ctl.v:82" *) _078_[15] : 1'bx;
  assign _078_[0] = _045_ ? (* src = "cordic_ctl.v:83" *) _077_[0] : 1'bx;
  assign _078_[1] = _045_ ? (* src = "cordic_ctl.v:83" *) _077_[1] : 1'bx;
  assign _078_[2] = _045_ ? (* src = "cordic_ctl.v:83" *) _077_[2] : 1'bx;
  assign _078_[3] = _045_ ? (* src = "cordic_ctl.v:83" *) _077_[3] : 1'bx;
  assign _078_[15] = _045_ ? (* src = "cordic_ctl.v:83" *) _077_[15] : 1'bx;
  assign _081_[0] = _045_ ? (* src = "cordic_ctl.v:83" *) _080_[0] : 1'bx;
  assign _081_[1] = _045_ ? (* src = "cordic_ctl.v:83" *) _080_[1] : 1'bx;
  assign _081_[2] = _045_ ? (* src = "cordic_ctl.v:83" *) _080_[2] : 1'bx;
  assign _081_[3] = _045_ ? (* src = "cordic_ctl.v:83" *) _080_[3] : 1'bx;
  assign _081_[4] = _045_ ? (* src = "cordic_ctl.v:83" *) _080_[4] : 1'bx;
  assign _081_[15] = _045_ ? (* src = "cordic_ctl.v:83" *) _080_[15] : 1'bx;
  assign _012_[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _082_[0] : 1'bx;
  assign _012_[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _082_[1] : 1'bx;
  assign _012_[2] = _043_ ? (* src = "cordic_ctl.v:81" *) _082_[2] : 1'bx;
  assign _012_[3] = _043_ ? (* src = "cordic_ctl.v:81" *) _082_[3] : 1'bx;
  assign _012_[4] = _043_ ? (* src = "cordic_ctl.v:81" *) _082_[4] : 1'bx;
  assign _012_[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _082_[15] : 1'bx;
  assign _062_[0] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[0] : 1'bx;
  assign _062_[1] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[1] : 1'bx;
  assign _062_[2] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[2] : 1'bx;
  assign _062_[3] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[3] : 1'bx;
  assign _062_[4] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[4] : 1'bx;
  assign _062_[5] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[5] : 1'bx;
  assign _062_[6] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[6] : 1'bx;
  assign _062_[7] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[7] : 1'bx;
  assign _062_[8] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[8] : 1'bx;
  assign _062_[9] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[9] : 1'bx;
  assign _062_[10] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[10] : 1'bx;
  assign _062_[11] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[11] : 1'bx;
  assign _062_[12] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[12] : 1'bx;
  assign _062_[13] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[13] : 1'bx;
  assign _062_[14] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[14] : 1'bx;
  assign _062_[15] = _038_ ? (* src = "cordic_ctl.v:72" *) _061_[15] : 1'bx;
  assign _082_[0] = _044_ ? (* src = "cordic_ctl.v:82" *) _081_[0] : 1'bx;
  assign _082_[1] = _044_ ? (* src = "cordic_ctl.v:82" *) _081_[1] : 1'bx;
  assign _082_[2] = _044_ ? (* src = "cordic_ctl.v:82" *) _081_[2] : 1'bx;
  assign _082_[3] = _044_ ? (* src = "cordic_ctl.v:82" *) _081_[3] : 1'bx;
  assign _082_[4] = _044_ ? (* src = "cordic_ctl.v:82" *) _081_[4] : 1'bx;
  assign _082_[15] = _044_ ? (* src = "cordic_ctl.v:82" *) _081_[15] : 1'bx;
  assign _013_[0] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[0] : 1'bx;
  assign _013_[1] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[1] : 1'bx;
  assign _013_[2] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[2] : 1'bx;
  assign _013_[3] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[3] : 1'bx;
  assign _013_[4] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[4] : 1'bx;
  assign _013_[5] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[5] : 1'bx;
  assign _013_[6] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[6] : 1'bx;
  assign _013_[7] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[7] : 1'bx;
  assign _013_[8] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[8] : 1'bx;
  assign _013_[9] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[9] : 1'bx;
  assign _013_[10] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[10] : 1'bx;
  assign _013_[11] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[11] : 1'bx;
  assign _013_[12] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[12] : 1'bx;
  assign _013_[13] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[13] : 1'bx;
  assign _013_[14] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[14] : 1'bx;
  assign _013_[15] = _036_ ? (* src = "cordic_ctl.v:71" *) _062_[15] : 1'bx;
  assign _075_[0] = _044_ ? (* src = "cordic_ctl.v:82" *) _074_[0] : 1'bx;
  assign _075_[1] = _044_ ? (* src = "cordic_ctl.v:82" *) _074_[1] : 1'bx;
  assign _075_[2] = _044_ ? (* src = "cordic_ctl.v:82" *) _074_[2] : 1'bx;
  assign _075_[15] = _044_ ? (* src = "cordic_ctl.v:82" *) _074_[15] : 1'bx;
  assign _015_[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _075_[0] : 1'bx;
  assign _015_[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _075_[1] : 1'bx;
  assign _015_[2] = _043_ ? (* src = "cordic_ctl.v:81" *) _075_[2] : 1'bx;
  assign _015_[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _075_[15] : 1'bx;
  assign _072_[0] = _047_ ? (* src = "cordic_ctl.v:85" *) _071_[0] : 1'bx;
  assign _072_[1] = _047_ ? (* src = "cordic_ctl.v:85" *) _071_[1] : 1'bx;
  assign _072_[2] = _047_ ? (* src = "cordic_ctl.v:85" *) _071_[2] : 1'bx;
  assign _072_[15] = _047_ ? (* src = "cordic_ctl.v:85" *) _071_[15] : 1'bx;
  assign _071_[0] = _048_ ? (* src = "cordic_ctl.v:86" *) _016_[0] : 1'b0;
  assign _071_[1] = _048_ ? (* src = "cordic_ctl.v:86" *) _016_[1] : 1'b0;
  assign _071_[2] = _048_ ? (* src = "cordic_ctl.v:86" *) _016_[15] : 1'b1;
  assign _071_[15] = _048_ ? (* src = "cordic_ctl.v:86" *) _016_[15] : 1'b0;
  assign _073_[0] = _046_ ? (* src = "cordic_ctl.v:84" *) _072_[0] : 1'bx;
  assign _073_[1] = _046_ ? (* src = "cordic_ctl.v:84" *) _072_[1] : 1'bx;
  assign _073_[2] = _046_ ? (* src = "cordic_ctl.v:84" *) _072_[2] : 1'bx;
  assign _073_[15] = _046_ ? (* src = "cordic_ctl.v:84" *) _072_[15] : 1'bx;
  assign _074_[0] = _045_ ? (* src = "cordic_ctl.v:83" *) _073_[0] : 1'bx;
  assign _074_[1] = _045_ ? (* src = "cordic_ctl.v:83" *) _073_[1] : 1'bx;
  assign _074_[2] = _045_ ? (* src = "cordic_ctl.v:83" *) _073_[2] : 1'bx;
  assign _074_[15] = _045_ ? (* src = "cordic_ctl.v:83" *) _073_[15] : 1'bx;
  assign _065_[0] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[0] : a_mpidiv2[0];
  assign _065_[1] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[1] : a_mpidiv2[1];
  assign _065_[2] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[2] : a_mpidiv2[2];
  assign _065_[3] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[3] : a_mpidiv2[3];
  assign _065_[4] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[4] : a_mpidiv2[4];
  assign _065_[5] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[5] : a_mpidiv2[5];
  assign _065_[6] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[6] : a_mpidiv2[6];
  assign _065_[7] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[7] : a_mpidiv2[7];
  assign _065_[8] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[8] : a_mpidiv2[8];
  assign _065_[9] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[9] : a_mpidiv2[9];
  assign _065_[10] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[10] : a_mpidiv2[10];
  assign _065_[11] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[11] : a_mpidiv2[11];
  assign _065_[12] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[12] : a_mpidiv2[12];
  assign _065_[13] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[13] : a_mpidiv2[13];
  assign _065_[14] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[14] : a_mpidiv2[14];
  assign _065_[15] = _038_ ? (* src = "cordic_ctl.v:72" *) _011_[15] : quadrant_0;
  assign _007_[0] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[0] : 1'bx;
  assign _007_[1] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[1] : 1'bx;
  assign _007_[2] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[2] : 1'bx;
  assign _007_[3] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[3] : 1'bx;
  assign _007_[4] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[4] : 1'bx;
  assign _007_[5] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[5] : 1'bx;
  assign _007_[6] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[6] : 1'bx;
  assign _007_[7] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[7] : 1'bx;
  assign _007_[8] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[8] : 1'bx;
  assign _007_[9] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[9] : 1'bx;
  assign _007_[10] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[10] : 1'bx;
  assign _007_[11] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[11] : 1'bx;
  assign _007_[12] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[12] : 1'bx;
  assign _007_[13] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[13] : 1'bx;
  assign _007_[14] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[14] : 1'bx;
  assign _007_[15] = _036_ ? (* src = "cordic_ctl.v:71" *) _065_[15] : 1'bx;
  assign _053_ = ~(* src = "cordic_ctl.v:87" *) _049_;
  assign _016_[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _070_[0] : 1'bx;
  assign _016_[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _070_[1] : 1'bx;
  assign _016_[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _070_[15] : 1'bx;
  assign _070_[0] = _044_ ? (* src = "cordic_ctl.v:82" *) _069_[0] : 1'bx;
  assign _070_[1] = _044_ ? (* src = "cordic_ctl.v:82" *) _069_[1] : 1'bx;
  assign _070_[15] = _044_ ? (* src = "cordic_ctl.v:82" *) _069_[15] : 1'bx;
  assign _069_[0] = _045_ ? (* src = "cordic_ctl.v:83" *) _068_[0] : 1'bx;
  assign _069_[1] = _045_ ? (* src = "cordic_ctl.v:83" *) _068_[1] : 1'bx;
  assign _069_[15] = _045_ ? (* src = "cordic_ctl.v:83" *) _068_[15] : 1'bx;
  assign _068_[0] = _046_ ? (* src = "cordic_ctl.v:84" *) _067_[0] : 1'bx;
  assign _068_[1] = _046_ ? (* src = "cordic_ctl.v:84" *) _067_[1] : 1'bx;
  assign _068_[15] = _046_ ? (* src = "cordic_ctl.v:84" *) _067_[15] : 1'bx;
  assign _067_[0] = _047_ ? (* src = "cordic_ctl.v:85" *) _066_[0] : 1'bx;
  assign _067_[1] = _047_ ? (* src = "cordic_ctl.v:85" *) _066_[1] : 1'bx;
  assign _067_[15] = _047_ ? (* src = "cordic_ctl.v:85" *) _066_[15] : 1'bx;
  assign _011_[0] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[0] : 1'bx;
  assign _011_[1] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[1] : 1'bx;
  assign _011_[2] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[2] : 1'bx;
  assign _011_[3] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[3] : 1'bx;
  assign _011_[4] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[4] : 1'bx;
  assign _011_[5] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[5] : 1'bx;
  assign _011_[6] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[6] : 1'bx;
  assign _011_[7] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[7] : 1'bx;
  assign _011_[8] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[8] : 1'bx;
  assign _011_[9] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[9] : 1'bx;
  assign _011_[10] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[10] : 1'bx;
  assign _011_[11] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[11] : 1'bx;
  assign _011_[12] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[12] : 1'bx;
  assign _011_[13] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[13] : 1'bx;
  assign _011_[14] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[14] : 1'bx;
  assign _011_[15] = _036_ ? (* src = "cordic_ctl.v:71" *) _064_[15] : 1'bx;
  assign _064_[0] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[0] : 1'bx;
  assign _064_[1] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[1] : 1'bx;
  assign _064_[2] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[2] : 1'bx;
  assign _064_[3] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[3] : 1'bx;
  assign _064_[4] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[4] : 1'bx;
  assign _064_[5] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[5] : 1'bx;
  assign _064_[6] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[6] : 1'bx;
  assign _064_[7] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[7] : 1'bx;
  assign _064_[8] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[8] : 1'bx;
  assign _064_[9] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[9] : 1'bx;
  assign _064_[10] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[10] : 1'bx;
  assign _064_[11] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[11] : 1'bx;
  assign _064_[12] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[12] : 1'bx;
  assign _064_[13] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[13] : 1'bx;
  assign _064_[14] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[14] : 1'bx;
  assign _064_[15] = _038_ ? (* src = "cordic_ctl.v:72" *) _063_[15] : 1'bx;
  assign _063_[0] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[0] : _087_[0];
  assign _063_[1] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[1] : _087_[1];
  assign _063_[2] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[2] : _087_[2];
  assign _063_[3] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[3] : _087_[3];
  assign _063_[4] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[4] : _087_[4];
  assign _063_[5] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[5] : _087_[5];
  assign _063_[6] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[6] : _087_[6];
  assign _063_[7] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[7] : _087_[7];
  assign _063_[8] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[8] : _087_[8];
  assign _063_[9] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[9] : _087_[9];
  assign _063_[10] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[10] : _087_[10];
  assign _063_[11] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[11] : _087_[11];
  assign _063_[12] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[12] : _087_[12];
  assign _063_[13] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[13] : _087_[13];
  assign _063_[14] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[14] : _087_[14];
  assign _063_[15] = _039_ ? (* src = "cordic_ctl.v:73" *) _013_[15] : _087_[15];
  assign n_a[0] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[0] : a_p[0];
  assign n_a[1] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[1] : a_p[1];
  assign n_a[2] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[2] : a_p[2];
  assign n_a[3] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[3] : a_p[3];
  assign n_a[4] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[4] : a_p[4];
  assign n_a[5] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[5] : a_p[5];
  assign n_a[6] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[6] : a_p[6];
  assign n_a[7] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[7] : a_p[7];
  assign n_a[8] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[8] : a_p[8];
  assign n_a[9] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[9] : a_p[9];
  assign n_a[10] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[10] : 1'b0;
  assign n_a[11] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[11] : 1'b0;
  assign n_a[12] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[12] : 1'b0;
  assign n_a[13] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[13] : 1'b0;
  assign n_a[14] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[14] : 1'b0;
  assign n_a[15] = _036_ ? (* src = "cordic_ctl.v:71" *) _007_[15] : 1'b0;
  assign n_quadrant[0] = _036_ ? (* src = "cordic_ctl.v:91" *) _009_[0] : 1'b0;
  assign n_quadrant[1] = _036_ ? (* src = "cordic_ctl.v:91" *) _009_[1] : 1'b0;
  assign _009_[0] = _036_ ? (* src = "cordic_ctl.v:91" *) _086_[0] : 1'bx;
  assign _009_[1] = _036_ ? (* src = "cordic_ctl.v:91" *) _086_[1] : 1'bx;
  assign atan[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[0] : 1'b0;
  assign atan[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[1] : 1'b0;
  assign atan[2] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[2] : 1'b1;
  assign atan[3] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[3] : 1'b0;
  assign atan[4] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[4] : 1'b0;
  assign atan[5] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[5] : 1'b1;
  assign atan[6] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[15] : 1'b1;
  assign atan[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _006_[15] : 1'b0;
  assign _006_[0] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[0] : 1'bx;
  assign _006_[1] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[1] : 1'bx;
  assign _006_[2] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[2] : 1'bx;
  assign _006_[3] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[3] : 1'bx;
  assign _006_[4] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[4] : 1'bx;
  assign _006_[5] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[5] : 1'bx;
  assign _006_[15] = _043_ ? (* src = "cordic_ctl.v:81" *) _085_[15] : 1'bx;
  assign _076_[0] = _047_ ? (* src = "cordic_ctl.v:85" *) _015_[0] : 1'b0;
  assign _076_[1] = _047_ ? (* src = "cordic_ctl.v:85" *) _015_[1] : 1'b0;
  assign _076_[2] = _047_ ? (* src = "cordic_ctl.v:85" *) _015_[2] : 1'b0;
  assign _076_[3] = _047_ ? (* src = "cordic_ctl.v:85" *) _015_[15] : 1'b1;
  assign _076_[15] = _047_ ? (* src = "cordic_ctl.v:85" *) _015_[15] : 1'b0;
  assign _077_[0] = _046_ ? (* src = "cordic_ctl.v:84" *) _076_[0] : 1'bx;
  assign _077_[1] = _046_ ? (* src = "cordic_ctl.v:84" *) _076_[1] : 1'bx;
  assign _077_[2] = _046_ ? (* src = "cordic_ctl.v:84" *) _076_[2] : 1'bx;
  assign _077_[3] = _046_ ? (* src = "cordic_ctl.v:84" *) _076_[3] : 1'bx;
  assign _077_[15] = _046_ ? (* src = "cordic_ctl.v:84" *) _076_[15] : 1'bx;
  assign _066_[0] = _048_ ? (* src = "cordic_ctl.v:86" *) _049_ : 1'bx;
  assign _066_[1] = _048_ ? (* src = "cordic_ctl.v:86" *) _053_ : 1'bx;
  assign _066_[15] = _048_ ? (* src = "cordic_ctl.v:86" *) 1'b0 : 1'bx;
  assign _086_[0] = _038_ ? (* src = "cordic_ctl.v:92" *) quadrant[0] : _019_[0];
  assign _086_[1] = _038_ ? (* src = "cordic_ctl.v:92" *) quadrant[1] : _019_[1];
  assign _057_ = ~(* src = "cordic_ctl.v:73" *) a[15];
  assign _054_ = ~(* src = "cordic_ctl.v:158" *) rd_nxy_p;
  assign _055_ = ~(* src = "cordic_ctl.v:162" *) quadrant_0;
  assign _056_ = ~(* src = "cordic_ctl.v:163" *) wr_axy_p;
  assign _091_[0] = ~(* src = "<techmap.v>:258" *) atan[0];
  assign _091_[1] = ~(* src = "<techmap.v>:258" *) atan[1];
  assign _091_[2] = ~(* src = "<techmap.v>:258" *) atan[2];
  assign _091_[3] = ~(* src = "<techmap.v>:258" *) atan[3];
  assign _091_[4] = ~(* src = "<techmap.v>:258" *) atan[4];
  assign _091_[5] = ~(* src = "<techmap.v>:258" *) atan[5];
  assign _091_[15] = ~(* src = "<techmap.v>:258" *) atan[15];
  assign _091_[6] = ~(* src = "<techmap.v>:258" *) atan[6];
  (* src = "cordic_ctl.v:114" *)
  always @(posedge ck)
      mkc <= _002_;
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[0] <= n_a[0];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[1] <= n_a[1];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[2] <= n_a[2];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[3] <= n_a[3];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[4] <= n_a[4];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[5] <= n_a[5];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[6] <= n_a[6];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[7] <= n_a[7];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[8] <= n_a[8];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[9] <= n_a[9];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[10] <= n_a[10];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[11] <= n_a[11];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[12] <= n_a[12];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[13] <= n_a[13];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[14] <= n_a[14];
  (* src = "cordic_ctl.v:50" *)
  always @(posedge ck)
      a[15] <= n_a[15];
  (* src = "cordic_ctl.v:119" *)
  always @(posedge ck)
      calc <= _000_;
  (* src = "cordic_ctl.v:55" *)
  always @(posedge ck)
      quadrant[0] <= n_quadrant[0];
  (* src = "cordic_ctl.v:55" *)
  always @(posedge ck)
      quadrant[1] <= n_quadrant[1];
  (* src = "cordic_ctl.v:124" *)
  always @(posedge ck)
      norm <= _003_;
  (* src = "cordic_ctl.v:60" *)
  always @(posedge ck)
      i[0] <= n_i[0];
  (* src = "cordic_ctl.v:60" *)
  always @(posedge ck)
      i[1] <= n_i[1];
  (* src = "cordic_ctl.v:60" *)
  always @(posedge ck)
      i[2] <= n_i[2];
  (* src = "cordic_ctl.v:129" *)
  always @(posedge ck)
      get <= _001_;
  (* src = "cordic_ctl.v:109" *)
  always @(posedge ck)
      place <= _004_;
  (* src = "cordic_ctl.v:104" *)
  always @(posedge ck)
      put <= _005_;
  assign _183_ = _189_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _204_;
  assign _184_ = _191_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _095_[3];
  assign _185_ = a[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _096_[2];
  assign _186_ = _096_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _096_[4];
  assign _187_ = a[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  a[6];
  assign _188_ = _096_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _096_[8];
  assign _189_ = _096_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _096_[10];
  assign _190_ = _096_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _096_[12];
  assign _191_ = _187_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _186_;
  assign _192_ = _189_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _188_;
  assign _193_ = _192_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[7];
  assign _194_ = _186_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[3];
  assign _195_ = _188_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[7];
  assign _196_ = _190_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[11];
  assign _197_ = _096_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[1];
  assign _198_ = _096_[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[3];
  assign _095_[6] = a[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[5];
  assign _199_ = _096_[8] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[7];
  assign _200_ = _096_[10] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[9];
  assign _201_ = _096_[12] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[11];
  assign _202_ = _096_[14] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _095_[13];
  assign _095_[1] = a[1] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _175_;
  assign _203_ = a[5] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _177_;
  assign _204_ = a[9] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _178_;
  assign _205_ = a[11] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _179_;
  assign _206_ = a[13] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _180_;
  assign _095_[3] = _176_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _181_;
  assign _207_ = _205_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _183_;
  assign _095_[7] = _182_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _184_;
  assign _095_[11] = _207_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _193_;
  assign _095_[5] = _203_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _194_;
  assign _095_[9] = _204_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _195_;
  assign _095_[13] = _206_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _196_;
  assign _095_[2] = a[2] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _197_;
  assign _095_[4] = a[4] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _198_;
  assign _095_[8] = a[8] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _199_;
  assign _095_[10] = a[10] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _200_;
  assign _095_[12] = a[12] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _201_;
  assign _095_[14] = a[14] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _202_;
  assign _058_ = calc |(* src = "cordic_ctl.v:67" *)  mkc;
  assign _037_ = _058_ ^(* src = "cordic_ctl.v:67" *)  1'b1;
  assign _030_ = calc &(* src = "cordic_ctl.v:73" *)  _057_;
  assign _039_ = _030_ ^(* src = "cordic_ctl.v:73" *)  1'b1;
  assign _031_ = calc &(* src = "cordic_ctl.v:74" *)  a[15];
  assign _040_ = _031_ ^(* src = "cordic_ctl.v:74" *)  1'b1;
  assign _036_ = get ^(* src = "cordic_ctl.v:91" *)  1'b1;
  assign _038_ = _027_ ^(* src = "cordic_ctl.v:92" *)  1'b1;
  assign _005_ = raz &(* src = "cordic_ctl.v:106" *)  n_put;
  assign _004_ = raz &(* src = "cordic_ctl.v:111" *)  n_place;
  assign _002_ = raz &(* src = "cordic_ctl.v:116" *)  n_mkc;
  assign _000_ = raz &(* src = "cordic_ctl.v:121" *)  n_calc;
  assign _003_ = raz &(* src = "cordic_ctl.v:126" *)  n_norm;
  assign _020_ = raz &(* src = "cordic_ctl.v:131" *)  n_get;
  assign _001_ = _020_ |(* src = "cordic_ctl.v:131" *)  fsm_def_14;
  assign _021_ = put &(* src = "cordic_ctl.v:158" *)  _054_;
  assign n_put = place |(* src = "cordic_ctl.v:158" *)  _021_;
  assign n_place = mkc &(* src = "cordic_ctl.v:159" *)  _051_;
  assign _022_ = calc &(* src = "cordic_ctl.v:160" *)  _052_;
  assign _023_ = mkc &(* src = "cordic_ctl.v:160" *)  _045_;
  assign n_mkc = _022_ |(* src = "cordic_ctl.v:160" *)  _023_;
  assign _024_ = norm &(* src = "cordic_ctl.v:161" *)  quadrant_0;
  assign _041_[1] = i[1] ^(* src = "cordic_ctl.v:161" *)  1'b1;
  assign _042_[2] = i[2] ^(* src = "cordic_ctl.v:161" *)  1'b1;
  assign _025_ = calc &(* src = "cordic_ctl.v:161" *)  _050_;
  assign n_calc = _024_ |(* src = "cordic_ctl.v:161" *)  _025_;
  assign _026_ = get &(* src = "cordic_ctl.v:162" *)  wr_axy_p;
  assign _027_ = norm &(* src = "cordic_ctl.v:162" *)  _055_;
  assign n_norm = _026_ |(* src = "cordic_ctl.v:162" *)  _027_;
  assign _028_ = get &(* src = "cordic_ctl.v:163" *)  _056_;
  assign _029_ = put &(* src = "cordic_ctl.v:163" *)  rd_nxy_p;
  assign n_get = _028_ |(* src = "cordic_ctl.v:163" *)  _029_;
  assign _017_[0] = i[0] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _017_[1] = i[1] ^(* src = "<techmap.v>:263" *)  i[0];
  assign _017_[2] = i[2] ^(* src = "<techmap.v>:263" *)  _088_[1];
  assign _093_[0] = a[0] ^(* src = "<techmap.v>:262" *)  _091_[0];
  assign _094_[1] = a[1] ^(* src = "<techmap.v>:262" *)  _091_[1];
  assign _094_[2] = a[2] ^(* src = "<techmap.v>:262" *)  _091_[2];
  assign _094_[3] = a[3] ^(* src = "<techmap.v>:262" *)  _091_[3];
  assign _094_[4] = a[4] ^(* src = "<techmap.v>:262" *)  _091_[4];
  assign _094_[5] = a[5] ^(* src = "<techmap.v>:262" *)  _091_[5];
  assign _094_[6] = a[6] ^(* src = "<techmap.v>:262" *)  _091_[6];
  assign _094_[7] = a[7] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[8] = a[8] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[9] = a[9] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[10] = a[10] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[11] = a[11] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[12] = a[12] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[13] = a[13] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[14] = a[14] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _094_[15] = a[15] ^(* src = "<techmap.v>:262" *)  _091_[15];
  assign _087_[0] = _093_[0] ^(* src = "<techmap.v>:263" *)  1'b1;
  assign _087_[1] = _094_[1] ^(* src = "<techmap.v>:263" *)  _092_[0];
  assign _087_[2] = _094_[2] ^(* src = "<techmap.v>:263" *)  _092_[1];
  assign _087_[3] = _094_[3] ^(* src = "<techmap.v>:263" *)  _092_[2];
  assign _087_[4] = _094_[4] ^(* src = "<techmap.v>:263" *)  _092_[3];
  assign _087_[5] = _094_[5] ^(* src = "<techmap.v>:263" *)  _092_[4];
  assign _087_[6] = _094_[6] ^(* src = "<techmap.v>:263" *)  _092_[5];
  assign _087_[7] = _094_[7] ^(* src = "<techmap.v>:263" *)  _092_[6];
  assign _087_[8] = _094_[8] ^(* src = "<techmap.v>:263" *)  _092_[7];
  assign _087_[9] = _094_[9] ^(* src = "<techmap.v>:263" *)  _092_[8];
  assign _087_[10] = _094_[10] ^(* src = "<techmap.v>:263" *)  _092_[9];
  assign _087_[11] = _094_[11] ^(* src = "<techmap.v>:263" *)  _092_[10];
  assign _087_[12] = _094_[12] ^(* src = "<techmap.v>:263" *)  _092_[11];
  assign _087_[13] = _094_[13] ^(* src = "<techmap.v>:263" *)  _092_[12];
  assign _087_[14] = _094_[14] ^(* src = "<techmap.v>:263" *)  _092_[13];
  assign _087_[15] = _094_[15] ^(* src = "<techmap.v>:263" *)  _092_[14];
  assign _136_[0] = a[0] &(* src = "<techmap.v>:260" *)  _091_[0];
  assign _136_[1] = a[1] &(* src = "<techmap.v>:260" *)  _091_[1];
  assign _136_[2] = a[2] &(* src = "<techmap.v>:260" *)  _091_[2];
  assign _136_[3] = a[3] &(* src = "<techmap.v>:260" *)  _091_[3];
  assign _136_[4] = a[4] &(* src = "<techmap.v>:260" *)  _091_[4];
  assign _136_[5] = a[5] &(* src = "<techmap.v>:260" *)  _091_[5];
  assign _136_[6] = a[6] &(* src = "<techmap.v>:260" *)  _091_[6];
  assign _136_[7] = a[7] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[8] = a[8] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[9] = a[9] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[10] = a[10] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[11] = a[11] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[12] = a[12] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[13] = a[13] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _136_[14] = a[14] &(* src = "<techmap.v>:260" *)  _091_[15];
  assign _018_[0] = a[0] ^(* src = "<techmap.v>:262" *)  atan[0];
  assign _090_[1] = a[1] ^(* src = "<techmap.v>:262" *)  atan[1];
  assign _090_[2] = a[2] ^(* src = "<techmap.v>:262" *)  atan[2];
  assign _090_[3] = a[3] ^(* src = "<techmap.v>:262" *)  atan[3];
  assign _090_[4] = a[4] ^(* src = "<techmap.v>:262" *)  atan[4];
  assign _090_[5] = a[5] ^(* src = "<techmap.v>:262" *)  atan[5];
  assign _090_[6] = a[6] ^(* src = "<techmap.v>:262" *)  atan[6];
  assign _090_[7] = a[7] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[8] = a[8] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[9] = a[9] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[10] = a[10] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[11] = a[11] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[12] = a[12] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[13] = a[13] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[14] = a[14] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _090_[15] = a[15] ^(* src = "<techmap.v>:262" *)  atan[15];
  assign _018_[1] = _090_[1] ^(* src = "<techmap.v>:263" *)  _089_[0];
  assign _018_[2] = _090_[2] ^(* src = "<techmap.v>:263" *)  _089_[1];
  assign _018_[3] = _090_[3] ^(* src = "<techmap.v>:263" *)  _089_[2];
  assign _018_[4] = _090_[4] ^(* src = "<techmap.v>:263" *)  _089_[3];
  assign _018_[5] = _090_[5] ^(* src = "<techmap.v>:263" *)  _089_[4];
  assign _018_[6] = _090_[6] ^(* src = "<techmap.v>:263" *)  _089_[5];
  assign _018_[7] = _090_[7] ^(* src = "<techmap.v>:263" *)  _089_[6];
  assign _018_[8] = _090_[8] ^(* src = "<techmap.v>:263" *)  _089_[7];
  assign _018_[9] = _090_[9] ^(* src = "<techmap.v>:263" *)  _089_[8];
  assign _018_[10] = _090_[10] ^(* src = "<techmap.v>:263" *)  _089_[9];
  assign _018_[11] = _090_[11] ^(* src = "<techmap.v>:263" *)  _089_[10];
  assign _018_[12] = _090_[12] ^(* src = "<techmap.v>:263" *)  _089_[11];
  assign _018_[13] = _090_[13] ^(* src = "<techmap.v>:263" *)  _089_[12];
  assign _018_[14] = _090_[14] ^(* src = "<techmap.v>:263" *)  _089_[13];
  assign _018_[15] = _090_[15] ^(* src = "<techmap.v>:263" *)  _089_[14];
  assign _089_[0] = a[0] &(* src = "<techmap.v>:260" *)  atan[0];
  assign _097_[1] = a[1] &(* src = "<techmap.v>:260" *)  atan[1];
  assign _097_[2] = a[2] &(* src = "<techmap.v>:260" *)  atan[2];
  assign _097_[3] = a[3] &(* src = "<techmap.v>:260" *)  atan[3];
  assign _097_[4] = a[4] &(* src = "<techmap.v>:260" *)  atan[4];
  assign _097_[5] = a[5] &(* src = "<techmap.v>:260" *)  atan[5];
  assign _097_[6] = a[6] &(* src = "<techmap.v>:260" *)  atan[6];
  assign _097_[7] = a[7] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[8] = a[8] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[9] = a[9] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[10] = a[10] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[11] = a[11] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[12] = a[12] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[13] = a[13] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _097_[14] = a[14] &(* src = "<techmap.v>:260" *)  atan[15];
  assign _096_[1] = a[1] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[2] = a[2] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[4] = a[4] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[5] = a[5] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[8] = a[8] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[9] = a[9] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[10] = a[10] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[11] = a[11] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[12] = a[12] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[13] = a[13] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[14] = a[14] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _096_[15] = a[15] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign a_mpidiv2[0] = a[0] ^(* src = "<techmap.v>:263" *)  1'b1;
  assign a_mpidiv2[1] = _096_[1] ^(* src = "<techmap.v>:263" *)  a[0];
  assign a_mpidiv2[2] = _096_[2] ^(* src = "<techmap.v>:263" *)  _095_[1];
  assign a_mpidiv2[3] = a[3] ^(* src = "<techmap.v>:263" *)  _095_[2];
  assign a_mpidiv2[4] = _096_[4] ^(* src = "<techmap.v>:263" *)  _095_[3];
  assign a_mpidiv2[5] = _096_[5] ^(* src = "<techmap.v>:263" *)  _095_[4];
  assign a_mpidiv2[6] = a[6] ^(* src = "<techmap.v>:263" *)  _095_[5];
  assign a_mpidiv2[7] = a[7] ^(* src = "<techmap.v>:263" *)  _095_[6];
  assign a_mpidiv2[8] = _096_[8] ^(* src = "<techmap.v>:263" *)  _095_[7];
  assign a_mpidiv2[9] = _096_[9] ^(* src = "<techmap.v>:263" *)  _095_[8];
  assign a_mpidiv2[10] = _096_[10] ^(* src = "<techmap.v>:263" *)  _095_[9];
  assign a_mpidiv2[11] = _096_[11] ^(* src = "<techmap.v>:263" *)  _095_[10];
  assign a_mpidiv2[12] = _096_[12] ^(* src = "<techmap.v>:263" *)  _095_[11];
  assign a_mpidiv2[13] = _096_[13] ^(* src = "<techmap.v>:263" *)  _095_[12];
  assign a_mpidiv2[14] = _096_[14] ^(* src = "<techmap.v>:263" *)  _095_[13];
  assign quadrant_0 = _096_[15] ^(* src = "<techmap.v>:263" *)  _095_[14];
  assign _019_[0] = quadrant[0] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _019_[1] = quadrant[1] ^(* src = "<techmap.v>:263" *)  quadrant[0];
  assign _088_[1] = i[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  i[0];
  assign _137_ = _094_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _092_[0];
  assign _138_ = _094_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _136_[2];
  assign _139_ = _094_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _136_[4];
  assign _140_ = _094_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _136_[6];
  assign _141_ = _094_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _136_[8];
  assign _142_ = _094_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _136_[10];
  assign _143_ = _094_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _136_[12];
  assign _144_ = _148_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _092_[1];
  assign _145_ = _150_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _168_;
  assign _146_ = _152_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _170_;
  assign _147_ = _154_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _092_[3];
  assign _148_ = _094_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _094_[2];
  assign _149_ = _094_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _094_[4];
  assign _150_ = _094_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _094_[6];
  assign _151_ = _094_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _094_[8];
  assign _152_ = _094_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _094_[10];
  assign _153_ = _094_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _094_[12];
  assign _154_ = _150_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _149_;
  assign _155_ = _152_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _151_;
  assign _156_ = _155_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[7];
  assign _157_ = _149_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[3];
  assign _158_ = _151_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[7];
  assign _159_ = _153_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[11];
  assign _160_ = _094_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[1];
  assign _161_ = _094_[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[3];
  assign _162_ = _094_[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[5];
  assign _163_ = _094_[8] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[7];
  assign _164_ = _094_[10] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[9];
  assign _165_ = _094_[12] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[11];
  assign _166_ = _094_[14] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _092_[13];
  assign _092_[0] = _136_[0] |(* src = "<techmap.v>:260|<techmap.v>:212" *)  _093_[0];
  assign _092_[1] = _136_[1] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _137_;
  assign _167_ = _136_[3] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _138_;
  assign _168_ = _136_[5] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _139_;
  assign _169_ = _136_[7] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _140_;
  assign _170_ = _136_[9] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _141_;
  assign _171_ = _136_[11] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _142_;
  assign _172_ = _136_[13] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _143_;
  assign _092_[3] = _167_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _144_;
  assign _173_ = _169_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _145_;
  assign _174_ = _171_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _146_;
  assign _092_[7] = _173_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _147_;
  assign _092_[11] = _174_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _156_;
  assign _092_[5] = _168_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _157_;
  assign _092_[9] = _170_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _158_;
  assign _092_[13] = _172_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _159_;
  assign _092_[2] = _136_[2] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _160_;
  assign _092_[4] = _136_[4] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _161_;
  assign _092_[6] = _136_[6] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _162_;
  assign _092_[8] = _136_[8] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _163_;
  assign _092_[10] = _136_[10] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _164_;
  assign _092_[12] = _136_[12] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _165_;
  assign _092_[14] = _136_[14] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _166_;
  assign _098_ = _090_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _089_[0];
  assign _099_ = _090_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _097_[2];
  assign _100_ = _090_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _097_[4];
  assign _101_ = _090_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _097_[6];
  assign _102_ = _090_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _097_[8];
  assign _103_ = _090_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _097_[10];
  assign _104_ = _090_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _097_[12];
  assign _105_ = _109_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _089_[1];
  assign _106_ = _111_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _129_;
  assign _107_ = _113_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _131_;
  assign _108_ = _115_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _089_[3];
  assign _109_ = _090_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _090_[2];
  assign _110_ = _090_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _090_[4];
  assign _111_ = _090_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _090_[6];
  assign _112_ = _090_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _090_[8];
  assign _113_ = _090_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _090_[10];
  assign _114_ = _090_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _090_[12];
  assign _115_ = _111_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _110_;
  assign _116_ = _113_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _112_;
  assign _117_ = _116_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[7];
  assign _118_ = _110_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[3];
  assign _119_ = _112_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[7];
  assign _120_ = _114_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[11];
  assign _121_ = _090_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[1];
  assign _122_ = _090_[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[3];
  assign _123_ = _090_[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[5];
  assign _124_ = _090_[8] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[7];
  assign _125_ = _090_[10] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[9];
  assign _126_ = _090_[12] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[11];
  assign _127_ = _090_[14] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_[13];
  assign _089_[1] = _097_[1] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _098_;
  assign _128_ = _097_[3] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _099_;
  assign _129_ = _097_[5] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _100_;
  assign _130_ = _097_[7] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _101_;
  assign _131_ = _097_[9] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _102_;
  assign _132_ = _097_[11] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _103_;
  assign _133_ = _097_[13] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _104_;
  assign _089_[3] = _128_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _105_;
  assign _134_ = _130_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _106_;
  assign _135_ = _132_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _107_;
  assign _089_[7] = _134_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _108_;
  assign _089_[11] = _135_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _117_;
  assign _089_[5] = _129_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _118_;
  assign _089_[9] = _131_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _119_;
  assign _089_[13] = _133_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _120_;
  assign _089_[2] = _097_[2] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _121_;
  assign _089_[4] = _097_[4] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _122_;
  assign _089_[6] = _097_[6] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _123_;
  assign _089_[8] = _097_[8] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _124_;
  assign _089_[10] = _097_[10] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _125_;
  assign _089_[12] = _097_[12] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _126_;
  assign _089_[14] = _097_[14] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _127_;
  assign _175_ = _096_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  a[0];
  assign _176_ = a[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  a[2];
  assign _177_ = _096_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  a[4];
  assign _178_ = _096_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  a[8];
  assign _179_ = _096_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  a[10];
  assign _180_ = _096_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  a[12];
  assign _181_ = _185_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _095_[1];
  assign _182_ = _187_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _203_;
  assign a_lt_0 = a[15];
  assign a_lt_0_p = a[15];
  assign a_mpidiv2[15] = quadrant_0;
  assign atan[14:7] = { atan[15], atan[15], atan[15], atan[15], atan[15], atan[15], atan[15], atan[15] };
  assign calc_p = calc;
  assign get_p = get;
  assign i_p = i;
  assign mkc_p = mkc;
  assign place_p = place;
  assign quadrant_p = quadrant;
  assign rok_nxy_p = put;
  assign rtldef_0 = raz;
  assign rtldef_1 = raz;
  assign rtldef_2 = raz;
  assign rtldef_3 = raz;
  assign rtldef_4 = raz;
  assign rtldef_5 = raz;
  assign rtlexts_0 = { 6'b000000, a_p };
  assign wok_axy_p = get;
endmodule
